# Generated by Django 4.1.3 on 2023-04-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_date_joined_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
