# Generated by Django 4.1.7 on 2023-04-04 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetail',
            name='created',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created',
        ),
        migrations.RemoveField(
            model_name='room',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_updated',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=256)),
                ('rating', models.IntegerField(default=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
