# Generated by Django 4.1.3 on 2023-04-27 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_roomtype_hotel_alter_reservation_arrive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrive_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 21, 59, 59, 609423)),
        ),
    ]
