# Generated by Django 4.1.3 on 2023-04-27 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_hotel_roomtype_hotel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='hotel_id',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrive_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 22, 2, 12, 661148)),
        ),
    ]
