# Generated by Django 4.1.3 on 2023-04-27 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_roomtype_hotel_roomtype_hotel_external_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='hotel_external',
            new_name='hotel',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrive_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 22, 48, 53, 361685)),
        ),
    ]
