# Generated by Django 4.1.3 on 2023-04-27 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_rename_hotel_external_roomtype_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrive_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 22, 52, 6, 150207)),
        ),
    ]
