# Generated by Django 4.1.3 on 2023-04-27 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_reservation_arrive_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrive_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 23, 2, 42, 57072)),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('id', 'room_type'), name='constraint_2'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(models.F('id'), models.F('hotel'), name='constraint_1'),
        ),
    ]
