# Generated by Django 4.1.3 on 2023-04-27 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_roomtype_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrive_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 23, 4, 16, 99436)),
        ),
    ]
