# Generated by Django 4.1.3 on 2023-04-30 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_room_floor_room_hotel_alter_reservation_arrive_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrive_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 7, 23, 44, 501515)),
        ),
    ]
