# Generated by Django 4.1.3 on 2023-04-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_remove_room_activate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrive_date',
            field=models.DateField(),
        ),
    ]
