# Generated by Django 4.1.3 on 2023-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_remove_reservation_arrive_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.TextField(choices=[('t1', 'single bedroom'), ('t2', 'double bedroom'), ('t3', 'queen size'), ('t4', 'king size'), ('t5', 'suite'), ('t6', 'apartment')], default='t1', max_length=3),
        ),
    ]
