# Generated by Django 4.1.3 on 2023-05-06 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_alter_reservation_special_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='booking.hotel'),
        ),
    ]
