# Generated by Django 4.1.3 on 2023-05-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_alter_reservation_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='meal_type',
            field=models.TextField(choices=[('no meal', 'Default Type'), ('breakfast', 'Meal Type 1'), ('dinner', 'Meal Type 2'), ('breakfast and dinner', 'Meal Type 3')], default='no meal', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.TextField(choices=[('not canceled', 'Not Cancelled'), ('cancelled', 'Cancelled')], default='not canceled', max_length=12),
        ),
    ]
