# Generated by Django 4.1.3 on 2023-05-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_alter_reservation_meal_type_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['created', 'id'], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.TextField(choices=[('not cancelled', 'Not Cancelled'), ('cancelled', 'Cancelled')], default='not cancelled', max_length=13),
        ),
    ]
